### ISSUE TITLE
14.3 Cargoのワークスペースの解説のオプションのミス？

### ISSUE THREAD

**Issue by altzweel** [rust-lang-ja/book-ja#10]
Cargoのワークスペースのページの[ワークスペース内に2番目のクレートを作成する](https://github.com/rust-lang-ja/book-ja/blob/second-edition-ja/second-edition/src/ch14-03-cargo-workspaces.md#%E3%83%AF%E3%83%BC%E3%82%AF%E3%82%B9%E3%83%9A%E3%83%BC%E3%82%B9%E5%86%85%E3%81%AB2%E7%95%AA%E7%9B%AE%E3%81%AE%E3%82%AF%E3%83%AC%E3%83%BC%E3%83%88%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B)
で、
```
$ cargo new add-one
     Created library `add-one` project
```

とありますが、ライブラリ を作るときは`--lib`は付けなくても良いんでしょうか？

実際試してたらバイナリクレートができたのと、英語版ではオプションが付いてたので、一応Issue立てました。

**Comment by tatsuya6502** [comment]
返信が遅くなってすみません。ご報告ありがとうございました。

おっしゃる通り最近のバージョンのCargoでは`--lib`オプションが必要ですね。修正します。

実はRust 1.24.1（2018年3月リリース）に同梱されていたCargo 0.25.0までは、`cargo new`のデフォルトが`--bin`ではなく`--lib`でした（[参考](https://blog.rust-lang.org/2018/03/29/Rust-1.25.html#cargo-features)）　おそらく該当のページを和訳したときはまだ`--lib`の方がデフォルトだったのだと思います。
