### ISSUE TITLE
訳語：rectangle 四角形（ch05-02，ch11-01）

### ISSUE THREAD

**Issue by scivola** [rust-lang-ja/book-ja#100]
ch05-02 および ch11-01 で，「rectangle」を「四角形」と訳していますが，正確には「長方形」ですね。

**Comment by scivola** [comment]
これは PR を作ればいいのか，と思い，初めてやってみました。
やり方など適当でない点がありましたらお教えください。

**Comment by tatsuya6502** [comment]
本件、 #101 のマージ前に「四角形」がなくなることを確認したのですが、 #101 と #103 をマージした後にch05-02を見たところ、まだ一箇所「四角形」が残っていますね。

> リスト5-8のコードはうまく動き、各寸法を与えて`area`関数を呼び出すことで四角形の面積を割り出しますが、
> 改善点があります。幅と高さは、組み合わせると一つの長方形を表すので、相互に関係があるわけです。

 #103 をマージする際に #101 との間にコンフリクトがあったので私の方で修正を試みましたが、そこで何かミスしたのかもしれません。最後の四角形については、私の方で修正します。
