### ISSUE TITLE
用語：「control flow」は「フロー制御」でよいか？

### ISSUE THREAD

**Issue by scivola** [rust-lang-ja/book-ja#108]
原文の「control flow」がほとんどの箇所で「フロー制御」と訳されているようです。
（文脈をよく見ていないので自信がありませんが）これは「制御構造」のことではないのでしょうか。
あるいは「制御フロー」かもしれませんが，「フロー制御」は通信用語で全然意味が違うように思います。

**Comment by tatsuya6502** [comment]
ご提案ありがとうございます。 #188 にて「control flow」の訳語を「制御フロー」に統一しました。
