### ISSUE TITLE
forewordのアップデート

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/book-ja#109]
forewardの内容を最新版にアップデートする。

- 対象ファイル：master-jaブランチの [foreword.md](https://github.com/rust-lang-ja/book-ja/blob/master-ja/src/foreword.md)
- mdbook-transcheck &mdash; 追加：0行、変更：1行、削除：0行

----

翻訳手順については [今後ドキュメント化する予定](https://github.com/rust-lang-ja/book-ja/issues/83) です。それまでの間、手順についてはSlack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by toku-sa-n** [comment]
取り組みます．アサインお願いします．

**Comment by tatsuya6502** [comment]
@toku-sa-n — アサインしました。よろしくお願いします。
