### ISSUE TITLE
validの和訳について

### ISSUE THREAD

**Issue by woodyZootopia** [rust-lang-ja/book-ja#16]
validを「合法な」と訳している例がたくさんあります。しかし、「合法な」という言葉だけから、「言語の文法に合致した」という意味を読み取るのは直感的ではありません。

「正しい」「文法的に正しい」「有効な」などの訳に統一し、この言葉を使わないのが適当ではないでしょうか。

**Comment by tatsuya6502** [comment]
ご指摘ありがとうございます。

現在の和訳を作成された方は、こちら（[rust-lang-ja](https://github.com/rust-lang-ja/)）にはいらっしゃらないので、「合法な」と訳した意図については確認できません。

[他のissueコメント](https://github.com/rust-lang-ja/book-ja/issues/15#issuecomment-601992615) でお伝えしたように、和訳を2018 editionに対応させると同時に、日本語訳も直していこうと考えています。その際に、いただいたご提案の訳を参考にしながら、わかりやすい日本語訳へと改善していこうと思います。

**Comment by woodyZootopia** [comment]
返信ありがとうございます。2018 editionにむけて訳も修正していくということ、了解しました。
