### ISSUE TITLE
2.3.2 乱数を生成する　のコードエラー

### ISSUE THREAD

**Issue by karasawasonshi** [rust-lang-ja/book-ja#174]
[https://github.com/rust-lang-ja/book-ja/blob/master-ja/docs/ch02-00-guessing-game-tutorial.html](2章のページ)にある922行目の乱数を生成するコードが間違ってました。

掲載内容は次のとおり
```
    let secret_number = rand::thread_rng().gen_range(1, 101);
```

正しいコードは以下のもの
```
    let secret_number = rand::thread_rng().gen_range((1..101));
```

**Comment by TonalidadeHidrica** [comment]
[2020年12月18日の v0.8.0 のアップデート](https://github.com/rust-random/rand/blob/master/CHANGELOG.md#rngs-1) で仕様が変わったようですね。

**Comment by karasawasonshi** [comment]
言語仕様から変わってたんですね。ありがとうございました。

**Comment by TonalidadeHidrica** [comment]
いいえ、変わったのは「言語仕様」でなく「ライブラリ」、つまり Rust 言語のコアの外側にあるものです。
いずれにせよ、これを修正しない理由にはならないと思います。
（業務連絡：なお、本家の英語版はすでにアップデートされているようです）

**Comment by karasawasonshi** [comment]
あ、ほんとですね。 `gen_range`関数の引数が変わってるだけですね。
説明ありがとうございます。
**gen_range(a, b) was replaced with gen_range(a..b) **

**Comment by tatsuya6502** [comment]
ご報告ありがとうございます。

本リポジトリーの作業がいろいろと滞ってしまっていますが、手が空きしだい対応していきますので、しばらくお待ちください。

**Comment by tatsuya6502** [comment]
本件ですが、以下のプルリクエストで対応する予定です。

- #181
