### ISSUE TITLE
「トレイト境界」という訳語

### ISSUE THREAD

**Issue by 747** [rust-lang-ja/book-ja#20]
Trait bound という用語に「トレイト境界」という訳語が宛てられていますが、（専門用語として確立しているのでなければ）あまり達意の訳とはいいがたい気がします。

私見で恐縮ですが、英語で "bound" といった時は、例えば敷地の境界線やベン図で集合を区切る線など、ある一定の広がりを持つものを想像しながら、それが属性として持つ「外縁」としてイメージされると思います。それに対して、日本語で「境界」という時は、「線」の意味が中心で、それが両側で何かと何かを分けているようなものというふうに想像されます。
（前者は「犯人」で後者は「犯罪者」に近いということもできます。「犯人を逮捕する」と「犯罪者を逮捕する」では想像する情景が違うと思います。）

単体で使われている時はそういうものなのかな、と思う程度ですが、他の概念との関連で「～に対するトレイト境界」とか「トレイト境界を含む～」などの場面で現れると、「トレイトを『分割』している？」とか「何かの『境界』をまたいでいる？」みたいに変な想像が働いてしまって、混乱を生みやすいと思います。

他の用語と紛らわしくならないのであれば、「境界」の代わりに例えば**限界**や**枠**、**範囲**などのほうがいい気がしますがいかがでしょうか。

**Comment by KeenS** [comment]
トレイト境界の訳語については過去にも議論されているので一度参照してみて下さい。
https://github.com/rust-lang-ja/the-rust-programming-language-ja/issues/153

私感ですが、トレイト境界が達意の訳でないという指摘には同意するものの、限界や枠、範囲よりは分かりやすいかなと思います。「日本語で「境界」という時は、「線」の意味が中心」というのはまさしく意図通りでして、トレイト境界は型パラメータの動く範囲をトレイトで線引きするための機能なので、ニュアンスというか、方向としては間違ってないように見えます。

リポジトリの方針としては @tatsuya6502 がself-assignしてるので恐らくそちらから回答があるかと思います。

**Comment by tatsuya6502** [comment]
ご提案ありがとうございました。

トレイト境界という語に対しては、伝わりにくいという意見があることは承知しています。が、これ自体は変更しないでおこうと思います。

- 過去2回議論し、いずれもトレイト境界が採用された。（[1回目][discussion1]、[2回目][discussion2]）
- 他言語の用語との整合性
    - 同様の機能がJavaではbounded type parameter  → 境界型パラメータ、Scalaではupper bound → 上限境界と訳されている。
- Rustの書籍との整合性
    - トレイト境界
        - 実践Rust入門（技術評論社 2019/05）
        - プログラミング言語Rust公式ガイド（アスキードワンゴ 2019/06）
    - トレイト制約（trait constraints?）
        - プログラミングRust（オライリー・ジャパン 2018/08）
    - （未確認）
        - Rustプログラミング入門（オーム社 2019/10）　
        - Rust入門　安全性を同時に満たすシステム開発言語（日経BP社 2020/03）
- Google検索の結果
    - 「Rust "トレイト境界"」 → about 356 results
    - 「Rust "トレイト制約"」 → about 110 results

[discussion1]: https://github.com/rust-lang-ja/the-rust-programming-language-ja/pull/38
[discussion2]: https://github.com/rust-lang-ja/the-rust-programming-language-ja/issues/153

一方でこちらの訳は変更する必要があると思います。

- トレイト境界を含む～
- ～に対するトレイト境界

特に前者はどういう状態なのか、私にもイメージできません。

原文を確認したところ、以下のようになっていました。

> we could specify that `T` has the trait bound `Clone` instead.
> `T`が`Clone`というトレイト境界を含むと指定することもできます。

> This works differently than defining a struct that uses a generic type parameter with trait bounds.
> これは、トレイト境界を含むジェネリックな型引数を使用する構造体を定義するのとは異なる動作をします。

原文には含むの意味合いはなさそうです。

「対する」の原文はこうです。

> Because of the trait bound on `T`, 
> `T`に対するトレイト境界のため

これらは以下のように修正しようと思います。

> we could specify that `T` has the trait bound `Clone` instead.
> `T`が`Clone`というトレイト境界を持つと指定することもできます。

> This works differently than defining a struct that uses a generic type parameter with trait bounds.
> これは、トレイト境界を伴うジェネリックな型引数を使用する構造体を定義するのとは異なる動作をします。

> Because of the trait bound on `T`, 
> `T`に付けられたトレイト境界のため

**Comment by 747** [comment]
こんな質問にすぐに回答がつくと思わず失礼いたしました。

書籍を含めRustではある程度定着している（？）訳語であること、ご確認いただきありがとうございます。また、訳文の修正に取り組んでいただきありがとうございます。

@KeenS さんには過去の議論を示していただきありがとうございます。それを見て、以前の議論でははっきりと触れられていなかったポイントがあると思いましたので、ここに書き残しておきたいと思います。
まず、自分の意図としては、前の議論にあるように trait bounds が「線」ではないとか、「制約」と訳すべきだと主張しているわけではありません。原語の "bound" も線ではあるので。
ところが英語の "bound" は日本語で近い言葉を探すと「際限」のようなもので、何かの範囲があり、それを規定するものとしての線が認められる場合に使われると思います。対して日本語の「境界」は英語の "border" にあたり、目の前に線だけが見えていて、それが何かというと二つのものを分ける性質のものだ、という文脈で使われます（「境界」を使うときは、普通「何の境界」ではなく「何と何との境界」を思い浮かべると思います）。
数値のように一次元のものは、切れ目があれば何であれ二つの領域が自動的に得られますが、trait bounds はどちらかというと座標平面のようなところの中から閉じた領域を切り出すようなイメージを持っています。そこで「境界」のように線だけを見るような言葉を使うと、それが本当は範囲をその外から規定するために行っているのだ、という、原語には含まれる観念が落ちてしまうため、ピンぼけして聞こえるのだと思います。（もっとも、この印象が誤りで、本当はスカラやグラフの切断のようにイメージすべきものであるなら、勉強不足をお詫びいたします）
とはいえ日本語で線の背後にある領域を見る、みたいな便利な用語が見つからないため、いっそ原コメントのように範囲を前面に出す方がいいのではないかと思った次第です。

**Comment by yuttie** [comment]
古い議論に遅れてきて何か言うのは申し訳ないのですが、私も境界という言葉に違和感をもっている1人です。

この語の訳に関して、どなたか元の英文の著者などと意味の理解について擦り合わせなどされたのでしょうか？
Issueを見ていると、他言語の日本語訳はこうだからとか、英日辞書だとこうだからという、日本サイドの都合しか考慮していないように見受けられました。

また、別のissueで配列の境界を理由として挙げられていましたが、あれを境界と訳すことと、Rustのboundを境界と訳すことでは、受け入れられ方が異なると思います。配列は境界ありきですが、boundの方は境界を作るという違いがあります。また、後者はさらに境界を作ることは最終目的ではなく、境界で区切られたどちらかに制限することが本質であると思います。
用途が異なる概念が、同じ訳語になっているのは混乱を生みませんでしょうか？
