### ISSUE TITLE
コンパイラのライフタイム推論に関する文が読みにくい

### ISSUE THREAD

**Issue by TonalidadeHidrica** [rust-lang-ja/book-ja#32]
「10.3. ライフタイムで参照を検証する」の以下の箇所について申し上げます：
https://github.com/rust-lang-ja/book-ja/blame/second-edition-ja/second-edition/src/ch10-03-lifetime-syntax.md#L842-852

この文の、特に以下の文が特に読みにくいものとなっています：

> この場合、推論ではなく、コンパイラは、参照がお互いにどう関係するかを指定するライフタイム注釈を追記することで、 解決できるエラーを与えます。

対応する英語原文は以下のとおりです：

> In this case, instead of guessing, the compiler will give you an error that you can resolve by adding the lifetime annotations that specify how the references relate to each other.

文が読みにくい理由としては以下のような点が挙げられると思います：

* instead of guessing が文に唐突に「推論ではなく」として現れている
* 「追記する」と「解決できる」の主語がわかりにくい（youを極力省略した結果余計にわかりにくくなっている）

特に思ったのですが、この文の1つ目の that は、本来は非制限用法で書かれていたのではないでしょうか？　というのも、制限用法として解釈すると「解決できるエラー（だけ）を与える」と読み取られるからです。Rust初心者なので自信はないのですが、コンパイラが解決できないからユーザーに解決を迫るのですよね。それを踏まえると、この文はこのように解釈されると思いますが、正しいでしょうか？

> In this case, instead of guessing, the compiler will give you an error, which you can resolve by adding the lifetime annotations that specify how the references relate to each other.

> この場合コンパイラは、それらを推測するのではなくエラーを与えます。これらは、参照がお互いにどう関係するかを指定するライフタイム注釈を追記することで解決できます。

**Comment by tatsuya6502** [comment]
ご提案、ありがとうございます！

このSecond Editionの翻訳者が原文をどう解釈されたのかは、いまとなっては分かりません。その方は、このリポジトリにはいらっしゃらず、また、[以前、連絡を試みました](https://github.com/hazama-yuinyan/book/issues/49) が、今のところお返事はいただいていません。私自身も現在の訳には分かりづらいところがあったり、重大ではないものの誤訳があったりすることを認識しています。

ですから、TonalidadeHidricaさんにご説明いただいた内容については私も100%同意します。ご提案いただいた訳をぜひ採用させてください。

> 特に思ったのですが、この文の1つ目の that は、本来は非制限用法で書かれていたのではないでしょうか？　というのも、制限用法として解釈すると「解決できるエラー（だけ）を与える」と読み取られるからです。

本来は非制限用法という解釈で問題ないと思います。アメリカ英語の口語では ", which" よりも "that" が好まれる傾向があり、本来は ", which" が使えないはずの用法でも使われることはあると思います。

なお、このときに表示されるエラーは [E0495 (Cannot infer an appropriate lifetime)](https://doc.rust-lang.org/error-index.html#E0495) です。E0495は「参照がお互いにどう関係するかを指定するライフタイム注釈を追記する」ことで解決できる場合もありますし、ライフタイム要件を満足できるよう関数本体内などのコードを修正しなければ解決できない場合もあります。ですから「解決できるエラー（だけ）を与える」とはいえません。

**Comment by tatsuya6502** [comment]
> この場合コンパイラは、それらを推測するのではなくエラーを与えます。これらは、参照がお互いにどう関係するかを指定するライフタイム注釈を追記することで解決できます。

新しい訳ですが、私の方で修正＋反映しましょうか？　それとも @TonalidadeHidrica さんの方で修正してpull requestを提出しますか？（後者ですとコミットログにお名前が残ります）　どちらが良いかお知らせください。
