### ISSUE TITLE
appendix-04-macros.md: Broken Link (reference/macros.html)

### ISSUE THREAD

**Issue by mkontani** [rust-lang-ja/book-ja#46]
**付録D: マクロ**での[参考文献](https://doc.rust-jp.rs/reference/macros.html)のリンク先が存在しません。

### 該当箇所
https://github.com/rust-lang-ja/book-ja/blame/second-edition-ja/second-edition/src/appendix-04-macros.md#L228

[本家](https://doc.rust-lang.org/1.30.0/book/second-edition/appendix-04-macros.html)では以下を参照しているようです
https://doc.rust-lang.org/1.30.0/reference/macros.html

**Comment by tatsuya6502** [comment]
ご報告いただき、ありがとうございました。

遅くなってしまいましたが、リンク切れを直しました。
- 付録D: マクロ &mdash; [一般的なメタプログラミングのために`macro_rules!`で宣言的なマクロ](https://doc.rust-jp.rs/book/second-edition/appendix-04-macros.html#a%E4%B8%80%E8%88%AC%E7%9A%84%E3%81%AA%E3%83%A1%E3%82%BF%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E3%81%AE%E3%81%9F%E3%82%81%E3%81%ABmacro_rules%E3%81%A7%E5%AE%A3%E8%A8%80%E7%9A%84%E3%81%AA%E3%83%9E%E3%82%AF%E3%83%AD)
