### ISSUE TITLE
raw identifierをどう訳すか

### ISSUE THREAD

**Issue by woodyZootopia** [rust-lang-ja/book-ja#67]
rust 2018 editionで追加された "raw identifier"という単語は、おそらく訳語が存在しません。
ドキュメントを訳すに当たり統一した訳語を考えたいですが、いいアイデアはありますか？
自分としては、

* 訳さない：「raw identifier」
* 訳す：「生指定子」「直接指定子」
* raw文字列にならって：「raw指定子」

あたりが良いと思います。

参考：
TRPL 2018におけるraw identifierの解説: https://doc.rust-lang.org/book/appendix-01-keywords.html#raw-identifiers
raw identifierのRFC: https://github.com/rust-lang/rfcs/blob/master/text/2151-raw-identifiers.md

**Comment by tatsuya6502** [comment]
identifierの部分ですが、訳すなら「識別子」になります。指定子はspecifierの訳として使っています。例：ライフタイム指定子/lifetime specifier

rawはsecond editionだと「生」が使われているようです。
- raw pointer/生ポインタ　（ch16-04, ch19-01, appendix-01, appendix-02）
- raw string/生の文字列　（ch08-02）

ですから、この流れでいくと「生識別子」か「生の識別子」と訳すのかなと思います。

ただ、その一方で、woodyさんも例に挙げられているとおり、他の言語などでは「raw文字列」という訳もよく使われているようなので、「raw識別子」でもいいような気がします。

ちなみにRustの世界ですと、生ポインタという言葉は記事や会話に頻繁に登場するので、この訳自体はポピュラーな気がします。raw stringやraw identifierという言葉は普段ほとんど目にしないので、Rustの世界で決まった訳はなさそうに思えます。

自分の執筆した書籍ではどうしたのか調べたところ、こうなってました。

- raw pointer/生ポインタ
- raw string/raw文字列
- raw identifier/生識別子

> （2-5-3項）“r#付きの識別子は生識別子（raw identifier）と呼ばれ、言語の予約語と重なっていても識別子だと認識されます”
> 
> Excerpt From: κeen、河野達也、小松礼人. “実践Rust入門 ［言語仕様から開発手法まで］”

**Comment by woodyZootopia** [comment]
@tatsuya6502 返信ありがとうございます。
> identifierの部分ですが、訳すなら「識別子」になります。指定子はspecifierの訳として使っています。例：ライフタイム指定子/lifetime specifier
完全にそのとおりですね。間違えてました。

> 生ポインタという言葉は記事や会話に頻繁に登場する
たしかにそうですね。では「生識別子」と訳そうと思います。
せっかくなので対訳表に追加したほうが良いですかね？

**Comment by tatsuya6502** [comment]
> では「生識別子」と訳そうと思います。

良いと思います。

> せっかくなので対訳表に追加したほうが良いですかね？

はい。ぜひお願いします。

**Comment by woodyZootopia** [comment]
TrasnlaionTable.mdがsecond-edition-jaブランチにはあるんですけど、master-jaブランチからは消えちゃってたのでコピーした上で修正しました。: #68
