### ISSUE TITLE
原版の日本語翻訳版へのリンク更新について

### ISSUE THREAD

**Issue by toku-sa-n** [rust-lang-ja/book-ja#8]
原版の，各言語への翻訳のリンク集のページ内で，日本語版へのリンクがhazama-yuinyanさんのリポジトリへのリンクのままとなっています（https://doc.rust-lang.org/book/appendix-06-translation.html）．
これをrust-lang-ja/book-ja（つまりこのリポジトリ）へのリンクにするようプルリクエストを送ったほうがいいでしょうか．

**Comment by raehik** [comment]
こちらに修正しました https://github.com/rust-lang/book/pull/2221

**Comment by toku-sa-n** [comment]
確認しました、ありがとうございます。
