### ISSUE TITLE
付録Fの翻訳

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/book-ja#87]
付録Fの内容を最新版にアップデートする。

- 対象ファイル：master-jaブランチの [appendix-06-translation.md](https://github.com/rust-lang-ja/book-ja/blob/master-ja/src/appendix-06-translation.md)

----

翻訳手順については [今後ドキュメント化する予定](https://github.com/rust-lang-ja/book-ja/issues/83) です。それまでの間、手順についてはSlack rust-jpのtranslationチャンネルで質問してください。[登録URL](https://rust-jp.herokuapp.com/)

**Comment by woodyZootopia** [comment]
夏休みが終わる前にこれも終わらせちゃいます。アサインお願いします。

**Comment by tatsuya6502** [comment]
@woodyZootopia — アサインしました。よろしくお願いします。
