### ISSUE TITLE
第2版TRPL 各ページの<head>にnoindexを追記する

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/book-ja#89]
最新版（2018 Edition）の公開後、第2版（second edition）は全ての検索エンジンでクローリング対象外にしたい。第2版各ページの `<head>` に `<meta name="robots" content="noindex">` を追記する。

**Comment by toku-sa-n** [comment]
#88 を行なった後でないと，HTMLの自動生成によって上書きされてしまわないでしょうか？

**Comment by tatsuya6502** [comment]
コメントありがとうございます。本件が具体的にどうやったら実現できるかまだ調べていないのですが、できれば、mdBookが使用しているテンプレートのようなものを修正することで、mdBookが生成したHTMLに`noindex`が自動挿入されるようにしたいと考えています。

もし、それができなくて、生成後のHTMLを直接編集することになったら、おっしゃる通り #88 を行った後でないとまずそうです。

**Comment by tatsuya6502** [comment]
メモ：
TRPL2のビルドで使用しているmdBookのバージョンは0.1.7

- CI用イメージの[Dockerfile](https://github.com/rust-lang-ja/circleci-images/blob/trpl2/docker/Dockerfile#L8)
- [mdBook 0.1.7のソースコード](https://github.com/rust-lang/mdBook/tree/v0.1.7)

このバージョンが[Theme](https://rust-lang.github.io/mdBook/format/theme/index.html)にどこまで対応しているかは調査が必要。

**Comment by tatsuya6502** [comment]
本件、mdBookが使用しているテンプレートを修正することで、mdBookが生成したHTMLにnoindexを自動挿入できることが確認できた。Pull request #107 で修正する。
