### ISSUE TITLE
TRPL以外の公式ドキュメントへのリンクが切れている

### ISSUE THREAD

**Issue by tatsuya6502** [rust-lang-ja/book-ja#90]
現在翻訳中の最新版（2018 Edition対応、master-jaブランチ）には、stdクレートやThe Unstable Bookなどの「TRPL以外」の公式ドキュメントへのリンクが含まれているページがある。それらのリンクがリンク切れになっている。

リンク切れになる理由は、URLが相対URLで記述されているため。和訳ドキュメントのサイト（doc.rust-jp.rs）ではそれらのドキュメントをホスティングしていないのでリンク切れになる。

**例**

```
src/ch08-00-common-collections.md
48:[collections]: ../../std/collections/index.html
```

調べたところ以下のMarkdownファイルに相対URLが含まれていることがわかった。これらのファイルの修正が必要となる。

- [x] appendix-01-keywords.md
- [ ] ch02-00-guessing-game-tutorial.md
- [x] ch06-01-defining-an-enum.md
- [x] ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
- [x] ch08-00-common-collections.md
- [x] ch11-01-writing-tests.md

**上のリストを得るために使用したコマンド**

```
$ rg -l --pcre2 '\.\./(?!listings)\S*\.html' src | sort
src/appendix-01-keywords.md
src/ch02-00-guessing-game-tutorial.md
src/ch06-01-defining-an-enum.md
src/ch07-04-bringing-paths-into-scope-with-the-use-keyword.md
src/ch08-00-common-collections.md
src/ch11-01-writing-tests.md
```

**Comment by toku-sa-n** [comment]
取り組みます．アサインお願いします．

**Comment by tatsuya6502** [comment]
@toku-sa-n 

アサインしました。よろしくお願いします。
